// Firefox exposes the promise-based `browser` namespace. Fall back to `chrome`
// so the rest of this file mirrors the Chromium build one-to-one.
const browser = globalThis.browser ?? globalThis.chrome;

/**
 * Background event page for MP3 Buddy Helper (Firefox).
 * Responsibilities:
 *   - register right-click context menus on install/startup
 *   - keep the action badge in sync with whether the active tab is supported
 *   - dispatch deep links (mp3buddy://download?...) on menu clicks
 */

const SUPPORTED_DOMAINS = [
  "youtube.com", "youtu.be",
  "bilibili.com", "b23.tv",
  "twitch.tv",
  "vimeo.com",
  "dailymotion.com",
  "nicovideo.jp",
  "twitter.com", "x.com",
  "instagram.com",
  "tiktok.com",
  "facebook.com", "fb.watch",
  "reddit.com",
  "soundcloud.com",
  "bandcamp.com",
  "crunchyroll.com",
];

const BADGE_COLOR = "#18A058";

const t = (key) => browser.i18n.getMessage(key) || key;

function isSupportedUrl(url) {
  if (!url) return false;
  try {
    const host = new URL(url).hostname;
    return SUPPORTED_DOMAINS.some((d) => host === d || host.endsWith("." + d));
  } catch {
    return false;
  }
}

function toNetscapeLine(c) {
  const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
  const flag = c.domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = c.secure ? "TRUE" : "FALSE";
  const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
  return `${domain}\t${flag}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`;
}

async function getCookieText(url) {
  const cookies = await browser.cookies.getAll({ url });
  if (!cookies?.length) return "";
  const header = "# Netscape HTTP Cookie File\n# Generated by MP3 Buddy Browser Extension\n\n";
  return header + cookies.map(toNetscapeLine).join("\n");
}

/**
 * Build a deep link. URLSearchParams handles `+`/`/`/`=` in base64 properly so
 * the receiver's URLSearchParams.get() returns the original string intact.
 */
function buildDeepLink(videoUrl, cookieText) {
  const params = new URLSearchParams();
  params.set("url", videoUrl);
  if (cookieText) {
    // btoa(encodeURIComponent(...)) round-trips UTF-8 safely through atob/decodeURIComponent.
    const b64 = btoa(encodeURIComponent(cookieText));
    params.set("cookies", b64);
  }
  return `mp3buddy://download?${params.toString()}`;
}

/**
 * Open a deep link without disrupting the user's active tab. We open it in a
 * background tab and close that tab shortly after - the OS protocol handler
 * intercepts the navigation, so the tab content never actually loads.
 */
async function dispatchDeepLink(deepLink) {
  try {
    const tab = await browser.tabs.create({ url: deepLink, active: false });
    setTimeout(() => {
      if (tab?.id) browser.tabs.remove(tab.id).catch(() => {});
    }, 1500);
    return true;
  } catch {
    return false;
  }
}

function notify(messageKey) {
  browser.notifications?.create({
    type: "basic",
    iconUrl: "icons/icon128.png",
    title: t("notifyTitle"),
    message: t(messageKey),
  });
}

async function sendToApp(videoUrl, { withCookies = true } = {}) {
  if (!isSupportedUrl(videoUrl)) {
    notify("notifyUnsupported");
    return;
  }
  const cookieText = withCookies ? await getCookieText(videoUrl) : "";
  const link = buildDeepLink(videoUrl, cookieText);
  const ok = await dispatchDeepLink(link);
  notify(ok ? "notifySent" : "notifyFailed");
}

// ---------- Context menus ----------

function setupMenus() {
  browser.contextMenus.removeAll(() => {
    browser.contextMenus.create({
      id: "ydl-send-page",
      title: t("menuSendPage"),
      contexts: ["page", "frame"],
      documentUrlPatterns: SUPPORTED_DOMAINS.map((d) => `*://*.${d}/*`),
    });
    browser.contextMenus.create({
      id: "ydl-send-link",
      title: t("menuSendLink"),
      contexts: ["link"],
    });
    browser.contextMenus.create({
      id: "ydl-send-selection",
      title: t("menuSendSelection"),
      contexts: ["selection"],
    });
  });
}

browser.runtime.onInstalled.addListener(setupMenus);
browser.runtime.onStartup.addListener(setupMenus);

browser.contextMenus.onClicked.addListener((info, tab) => {
  if (info.menuItemId === "ydl-send-page") {
    const target = info.frameUrl || info.pageUrl || tab?.url;
    if (target) sendToApp(target);
    return;
  }
  if (info.menuItemId === "ydl-send-link") {
    if (info.linkUrl) sendToApp(info.linkUrl);
    return;
  }
  if (info.menuItemId === "ydl-send-selection") {
    const text = (info.selectionText || "").trim();
    // selection might wrap http(s) URL with whitespace - use first token.
    const candidate = text.split(/\s+/).find((s) => /^https?:\/\//i.test(s));
    if (candidate) sendToApp(candidate);
    else notify("notifyUnsupported");
  }
});

// ---------- Action badge ----------

async function updateBadge(tabId, url) {
  const supported = isSupportedUrl(url);
  try {
    await browser.action.setBadgeBackgroundColor({ color: BADGE_COLOR, tabId });
    await browser.action.setBadgeText({ text: supported ? t("badgeOn") : "", tabId });
  } catch {
    // tab might be gone; ignore
  }
}

browser.tabs.onActivated.addListener(async ({ tabId }) => {
  try {
    const tab = await browser.tabs.get(tabId);
    updateBadge(tabId, tab.url);
  } catch {}
});

browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.url || changeInfo.status === "complete") {
    updateBadge(tabId, tab.url);
  }
});
